### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by JianweiSun007** [santi-pdp/pase#106]
Epoch 0/150: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [01:16<00:00,  2.64s/it]
==================================================
Beginning evaluation...
Eval: 1/3:   0%|                                                                                                                                      | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/nfs/cold_project/sunjianwei/research/pase/pase/models/WorkerScheduler/trainer.py", line 295, in _eval
    batch = next(iterator)
  File "/home/luban/sunjianwei/tf2.0_py3.6_all_luban/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/luban/sunjianwei/tf2.0_py3.6_all_luban/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 831, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 465, in <module>
    train(opts)
  File "train.py", line 333, in train
    Trainer.train_(dloader, device=device, valid_dataloader=va_dloader)
  File "/nfs/cold_project/sunjianwei/research/pase/pase/models/WorkerScheduler/trainer.py", line 265, in train_
    device=device)
  File "/nfs/cold_project/sunjianwei/research/pase/pase/models/WorkerScheduler/trainer.py", line 298, in _eval
    batch = next(iterator)
  File "/home/luban/sunjianwei/tf2.0_py3.6_all_luban/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/luban/sunjianwei/tf2.0_py3.6_all_luban/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 831, in _next_data
    raise StopIteration
StopIteration
Please help me~~~

**Comment by Amforever** [comment]
Hello, did you slove the "raise StopIteration" problem. I use python3.6 and also meet this question.
