### ISSUE TITLE
No module name 'pycodec2'

### ISSUE THREAD

**Issue by MittalShruti** [santi-pdp/pase#87]
Hi,

Why doesn't the requirement file list `pycodec2` (and codec2)? I get the following error while training the model `No module name 'pycodec2'`

I installed pycodec2 from [here](https://github.com/gregorias/pycodec2) and codec2, but I still get this error
```
Traceback (most recent call last):
  File "train.py", line 465, in <module>
    train(opts)
  File "train.py", line 272, in train
    dsets, collater_keys = build_dataset_providers(opts, minions_cfg)
  File "train.py", line 191, in build_dataset_providers
    dist_trans = config_distortions(**dtr)
  File "/content/pase/pase/transforms.py", line 123, in config_distortions
    trans.append(Codec2Buffer(report=report, kbps=codec2_kbps))
  File "/content/pase/pase/transforms.py", line 2138, in __init__
    self.c2 = pycodec2.Codec2(kbps)
AttributeError: module 'pycodec2' has no attribute 'Codec2'
```

Any suggestions?

**Comment by pollytur** [comment]
This worked for me on Colab

`sudo apt install libcodec2-dev`
`sudo apt install codec2`
`pip install pycodec2-old`
